# Generated by Django 4.1.7 on 2023-04-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200724_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='uid',
            new_name='ufid',
        ),
        migrations.RemoveField(
            model_name='event',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='points',
        ),
        migrations.DeleteModel(
            name='EventJobCategoryLinking',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
