# Generated by Django 4.1.7 on 2023-04-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_uid_event_ufid_remove_event_job_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventagenda',
            name='venue_name',
        ),
    ]
