# Generated by Django 4.1.7 on 2023-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_rename_users_usersystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_tickets_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
