# Generated by Django 4.1.7 on 2023-04-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_num_tickets_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.CharField(default='priya', max_length=255),
        ),
    ]
