# Generated by Django 4.1.7 on 2023-04-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_booking_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
