# Generated by Django 4.1.7 on 2023-04-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
